
nginx:
    build: ./docker/nginx
    ports:
        - 80:80
        - 443:443
    links:
        - php
    volumes_from:
        - app
    volumes:
        - ./docker/nginx/conf/:/etc/nginx/conf.d/
        - ./app/server/log/:/var/log/nginx/
    env_file: ./app/.env
    command: /bin/bash -c "envsubst '$$SERVER_PORT $$SERVER_SECURE_PORT $$SERVER_NAME $$SERVER_ALIAS $$DOCUMENT_ROOT $$PHP_PORT $$INCLUDE_PATH' < /etc/nginx/conf.d/server.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
php:
    build: ./docker/php
    expose:
        - 9000
    links:
        - mysql
    volumes_from:
        - app

app:
    image: php:fpm
    volumes:
        - ./app/:/app
    working_dir: /app
    command: "true"

mysql:
    image: mariadb:latest
    volumes:
        - ./docker/data:/docker-entrypoint-initdb.d
    volumes_from:
        - data
    ports:
        - 3306:3306
    env_file: ./app/.env

data:
    image: mariadb:latest
    volumes:
        - /var/lib/mysql
    command: "true"

composer:
    image: composer:latest
    volumes_from:
        - app
    working_dir: /app
    command: install

## Developer Tools
npm:
    image: node:latest
    volumes_from:
        - app
    links:
        - php
    working_dir: /app
    entrypoint: ['npm']

# gulp:
#     image: kahunacoder/docker-laravel-gulp
#     volumes_from:
#         - app
#     ports:
#         - "3000:3000"
#         - "3001:3001"
#     working_dir: /app
#     entrypoint: ['gulp']
